from typing import Dict

from gsuid_core.data_store import get_res_path
from gsuid_core.utils.plugins_config.models import (
    GSC,
    GsBoolConfig,
    GsDivider,
    GsImageConfig,
    GsIntConfig,
    GsListStrConfig,
    GsStrConfig,
)

SHOW_CONFIG_PATH = get_res_path(["ChisaEating", "show"])

CONFIG_DEFAULT: Dict[str, GSC] = {
    "_DividerScope": GsDivider("使用范围", ""),
    "forward_long_text": GsBoolConfig("长文本转发", "帮助和商会清单较长时优先使用合并转发", True),
    "convert_meme_to_gif": GsBoolConfig("表情包自动转 GIF", "启用后尝试将静态附加表情转换为 GIF；主菜图片不受影响", True),
    "enable_ai": GsBoolConfig("启用智能拟人回复", "预留 AI 回复开关；关闭时使用本地文案", False),
    "ai_probability": GsIntConfig("AI 回复概率 %", "启用智能回复后，使用 AI 生成文案的概率", 5),
    "admin_users": GsListStrConfig("资源管理用户", "允许使用加菜、上传厨师和图库管理的用户 ID；主人始终允许", []),
    "enable_workshop": GsBoolConfig("启用创意工坊", "允许在 WebUI 中使用创意工坊资源", False),
    "enable_skin": GsBoolConfig("启用主题皮肤", "启用 ChisaEating WebUI 主题皮肤设置", True),
    "webui_username": GsStrConfig("WebUI 用户名", "ChisaEating 独立 WebUI 登录用户名", "admin"),
    "webui_password": GsStrConfig("WebUI 密码", "ChisaEating 独立 WebUI 登录密码；请勿与账号密码共用", "", secret=True),
    "blacklist_groups": GsListStrConfig("群聊黑名单列表", "填写需要屏蔽的群号，一行一个", []),
    "enable_whitelist": GsBoolConfig("启用群聊白名单", "开启后只有白名单内的群组可触发功能", False),
    "whitelist_groups": GsListStrConfig("群聊白名单列表", "填写允许使用的群号，一行一个", []),

    "_DividerActiveWorld": GsDivider("默认世界", ""),
    "active_world": GsStrConfig("默认激活世界", "可选：鸣潮、原神世界、终末地、崩坏：星穹铁道或对应 world1~world5", "world1"),
    "weight_3d": GsIntConfig("三次元池权重", "大乱斗模式下三次元文字池的抽取权重", 70),
    "weight_world1": GsIntConfig("世界1池权重", "大乱斗模式下世界1的抽取权重", 20),
    "weight_world2": GsIntConfig("世界2池权重", "大乱斗模式下世界2的抽取权重", 5),
    "weight_world3": GsIntConfig("世界3池权重", "大乱斗模式下世界3的抽取权重", 5),
    "weight_world4": GsIntConfig("世界4池权重", "大乱斗模式下世界4的抽取权重", 0),
    "weight_world5": GsIntConfig("世界5池权重", "大乱斗模式下世界5的抽取权重", 0),

    "_DividerWorld1": GsDivider("世界 1：鸣潮", ""),
    "world1_name": GsStrConfig("世界1名称", "世界1的主名称", "鸣潮"),
    "world1_aliases": GsListStrConfig("世界1别名", "触发世界1特产的关键词，如：鸣潮特产", ["鸣潮", "索拉里斯"]),
    "world1_selfnames": GsListStrConfig("世界1推荐官自称池", "推荐官随机选取一个自称", ["爱弥斯", "小爱", "雪绒豹豹"]),
    "world1_food_text": GsListStrConfig("世界1文字食物池", "无图片时也能推荐的鸣潮特产文字列表", ["香柠切片", "冷调激浪", "今州排骨", "龙吐珠"]),
    "world1_drink_text": GsListStrConfig("世界1文字饮品池", "鸣潮特色饮品文字列表", ["今州特调", "清神茶"]),
    "world1_dark_text": GsListStrConfig("世界1文字黑暗料理池", "鸣潮的危险特产", ["工业爆炸物", "清汤变异巨蜥", "异种残响烤串"]),

    "_DividerWorld2": GsDivider("世界 2：原神", ""),
    "world2_name": GsStrConfig("世界2名称", "世界2的主名称", "原神世界"),
    "world2_aliases": GsListStrConfig("世界2别名", "触发世界2特产的关键词", ["原神", "提瓦特"]),
    "world2_selfnames": GsListStrConfig("世界2推荐官自称池", "", ["派蒙", "本向导"]),
    "world2_food_text": GsListStrConfig("世界2文字食物池", "", ["甜甜花酿鸡", "蜜酱胡萝卜煎肉", "水煮黑背鲈", "摩拉肉"]),
    "world2_drink_text": GsListStrConfig("世界2文字饮品池", "", ["蒲公英酒", "苹果酿", "莓果味汽水"]),
    "world2_dark_text": GsListStrConfig("世界2文字黑暗料理池", "", ["奇怪的烤肉排", "微妙的甜甜花酿鸡", "散发诡异气息的冷面"]),

    "_DividerCustomWorld": GsDivider("自定义世界", ""),
    "world3_name": GsStrConfig("世界3名称", "", "终末地"),
    "world3_aliases": GsListStrConfig("世界3别名", "", ["塔卫二", "帝江号"]),
    "world3_selfnames": GsListStrConfig("世界3推荐官自称池", "", ["管理员", "咕咕嘎嘎"]),
    "world3_food_text": GsListStrConfig("世界3文字食物池", "", []),
    "world3_drink_text": GsListStrConfig("世界3文字饮品池", "", []),
    "world3_dark_text": GsListStrConfig("世界3文字黑暗料理池", "", ["源石变异体残骸", "工业废液提取物"]),
    "world4_name": GsStrConfig("世界4名称", "", "崩坏：星穹铁道"),
    "world4_aliases": GsListStrConfig("世界4别名", "", ["星穹铁道", "星铁", "翁法罗斯"]),
    "world4_selfnames": GsListStrConfig("世界4推荐官自称池", "", ["列车长", "帕姆"]),
    "world4_food_text": GsListStrConfig("世界4文字食物池", "", ["列车组便当", "匹诺康尼糖球", "星际和平餐盒"]),
    "world4_drink_text": GsListStrConfig("世界4文字饮品池", "", ["苏乐达", "列车特调咖啡", "梦境饮料"]),
    "world4_dark_text": GsListStrConfig("世界4文字黑暗料理池", "", ["虚数泡面", "忆质炖汤"]),
    "world5_name": GsStrConfig("世界5名称", "", "绝区零"),
    "world5_aliases": GsListStrConfig("世界5别名", "", ["绝区零", "新艾利都"]),
    "world5_selfnames": GsListStrConfig("世界5推荐官自称池", "", ["绳匠", "Fairy"]),
    "world5_food_text": GsListStrConfig("世界5文字食物池", "", ["拉面", "咖啡", "六分街汉堡"]),
    "world5_drink_text": GsListStrConfig("世界5文字饮品池", "", ["咖啡", "气泡水", "苏打汽水"]),
    "world5_dark_text": GsListStrConfig("世界5文字黑暗料理池", "", ["以太爆米花", "空洞残骸炖汤"]),

    "_DividerTriggers": GsDivider("触发词", ""),
    "trigger_eat": GsListStrConfig("吃什么触发词", "包含这些词的消息触发食物推荐", ["吃什么", "吃啥", "吃点儿啥"]),
    "trigger_drink": GsListStrConfig("喝什么触发词", "", ["喝什么", "喝啥", "喝点儿啥"]),
    "trigger_dark": GsListStrConfig("黑暗料理触发词", "", ["来点黑暗料理", "黑暗料理"]),
    "trigger_common_eat": GsListStrConfig("现实食物触发词", "强制只从三次元卡池抽取食物", ["来点现实的食物", "来点三次元食物"]),
    "trigger_common_drink": GsListStrConfig("现实饮品触发词", "强制只从三次元卡池抽取饮品", ["来点现实的饮品", "来点三次元饮品"]),

    "_DividerTextPools": GsDivider("食物文字池", ""),
    "common_food_text": GsListStrConfig("三次元文字食物池", "无图片时推荐的现实食物", ["黄焖鸡米饭", "麻婆豆腐", "猪脚饭", "兰州牛肉面"]),
    "common_drink_text": GsListStrConfig("三次元文字饮品池", "", ["冰可乐", "乌龙茶", "冰吸生椰拿铁", "白开水"]),

    "_DividerProbability": GsDivider("概率与限流", ""),
    "global_meme_prob": GsIntConfig("常规表情包掉落概率 %", "0-100，普通推荐时附带发送表情包的概率", 30),
    "chef_meme_prob": GsIntConfig("厨师图鉴触发概率 %", "0-100，抽到厨师特制料理时展示厨师图的概率", 50),
    "interception_egg_chance": GsIntConfig("拦截彩蛋概率 %", "0-100，触发防刷屏时干饭人抢饭的概率", 50),
    "egg_prob": GsIntConfig("抢饭彩蛋概率 %", "0-100，每次推荐触发干饭人抢饭事件的概率", 10),
    "egg_pool": GsStrConfig("指定干饭人卡池", "留空=全员随机；多个名字用英文分号;隔开，如：千咲;派蒙", ""),
    "repeat_prob": GsIntConfig("摆烂复读概率 %", "0-100，推荐官陷入沉思并摆烂的概率", 10),
    "repeat_cooldown": GsIntConfig("摆烂复读冷却秒数", "触发一次摆烂后，该群聊的冷却时间（秒）", 60),
    "history_limit": GsIntConfig("群组防重复记忆长度", "最近 N 次推荐的食物不会重复出现，0 表示关闭", 30),
    "spam_threshold": GsIntConfig("防刷屏拦截触发次数", "60 秒内允许连续触发的最大次数", 3),

    "_DividerModes": GsDivider("推荐模式", ""),
    "mode_loyal": GsBoolConfig("誓死效忠模式", "开启后推荐官只推荐本世界的特产，不吃其他世界的", False),
    "mode_roller": GsBoolConfig("压路机模式", "只推荐二次元世界特产，屏蔽三次元普通食物", False),
    "mode_normie": GsBoolConfig("二刺猿不熟模式", "只推荐三次元普通食物，完全不推荐二次元特产", False),

    "_DividerTemplates": GsDivider("文案模板", ""),
    "generic_drink_templates": GsListStrConfig(
        "常规饮品推荐句式池",
        "抽中饮品时的后备句式，支持变量: {bot} {food}",
        ["铛铛！为你抽中了清爽的{food}！", "喝杯{food}解解渴吧！", "听{bot}的，今天来一杯{food}准没错~"],
    ),
    "crossover_templates": GsListStrConfig(
        "跨次元联动句式池",
        "跨界抽中其他世界食物时的句式，支持变量: {bot_a} {bot_b} {world_a} {world_b} {full_food_desc}",
        [
            "{bot_a}在穿过隧门的过程中，意外来到了{world_b}，并和{bot_b}一起吃了{full_food_desc}！",
            "{bot_a}为了寻找稀有食材，不小心跌入时空裂缝掉进{world_b}，被{bot_b}请客吃了一顿{full_food_desc}。",
            "次元壁破裂啦！{bot_a}从{world_b}顺手拿走了一份{full_food_desc}，并高高兴兴地带回了{world_a}。",
            "{bot_a}在探索新区域时迷路到了{world_b}，刚好遇到了正端着一盘{full_food_desc}的{bot_b}。",
        ],
    ),
    "dark_templates": GsListStrConfig(
        "黑暗料理句式池",
        "抽到黑暗料理时的句式，支持变量: {bot} {full_food_desc}",
        [
            "救命，这{full_food_desc}真的是碳基生物能咽下去的吗？！",
            "端上来的居然是{full_food_desc}...{bot}看了一眼，决定战术后仰。",
            "看到{full_food_desc}的那一刻，{bot}的沉默震耳欲聋...",
            "这盘{full_food_desc}散发着诡异的光芒，谁敢动筷子啊！",
            "警报！{bot}发现了一份危险的{full_food_desc}，建议立刻销毁！",
        ],
    ),
    "generic_templates": GsListStrConfig(
        "通用推荐句式池",
        "抽中三次元或普通食物时的句式，支持变量: {bot} {food}",
        [
            "铛铛！为你抽中了美味的{food}！",
            "经过深思熟虑，{bot}把这盘{food}端到了你面前。",
            "别纠结啦，今天就吃{food}吧！",
            "经过一番精密的摇号，{bot}宣布今天派发的美食是{food}！",
            "听{bot}的，今天尝试一下{food}准没错~",
        ],
    ),
}

APPEARANCE_CONFIG_DEFAULT: Dict[str, GSC] = {
    "ChisaHelpBannerBgUpload": GsImageConfig(
        "帮助横幅图",
        "自定义「千小妹还在吃帮助」顶部横幅图，留空或文件不存在时使用默认横幅",
        str(SHOW_CONFIG_PATH / "help_banner.png"),
        str(SHOW_CONFIG_PATH),
        "help_banner",
        "png",
    ),
    "ChisaHelpBgUpload": GsImageConfig(
        "帮助背景图",
        "自定义「千小妹还在吃帮助」整体背景图，留空或文件不存在时使用默认背景",
        str(SHOW_CONFIG_PATH / "help_bg.png"),
        str(SHOW_CONFIG_PATH),
        "help_bg",
        "png",
    ),
    "ChisaHelpIconUpload": GsImageConfig(
        "帮助头像",
        "自定义「千小妹还在吃帮助」左上角头像，建议使用方形图片",
        str(SHOW_CONFIG_PATH / "help_icon.png"),
        str(SHOW_CONFIG_PATH),
        "help_icon",
        "png",
    ),
    "ChisaHelpColumn": GsIntConfig(
        "帮助展示行数",
        "控制帮助图每组展示数量，默认 3，可按需要改成 4、5 等",
        3,
        10,
    ),
}
